 export const FiverrCategories = [

  {
    name: "Graphic arts",
    subcategories: [
      "Recorded",
      "Kinocut",
      "Lithography",
      "Serigraphy",
      "Woodcust",
      "Other",
    ],
  },
  {
    name: "Graphic design and digital design",
    subcategories: [
      "Typographic design",
      "Transmedia design",
      "Web/mobile design",
      "Iconography",
      "UX/UI",
      "Other",
      "Packagning design",
      "Corporate indetity dessign",
      "Editorial design",
      "Signage design",
      "Multimedia design",
      "Advertising design",
      "Technical design",
    ],
  },
    {
      name: "Multimedia",
      subcategories: [
        "Video Editing",
        "Editorial",
        "Interactive Application Programming",
        "Other",
      ],
    },
    {
      name: "Artificial Intelligence & Machine Learning",
      subcategories: [
        "Machine Learning (ML)",
        "Natural Language Processing (NLP)",
        "Computer Vision",
        "Reinforcement Learning",
        "Deep Learning",
        "AI Ethics & Policy",
        "AI in Robotics",
        "AI Programming & Algorithms",
        "Speech Recognition",
        "AI in Healthcare",
        "AI in Business",
        "AI Research & Development",
        "Other",
      ],
    },  
    {
      name: "Graphics & Design",
      subcategories: [
        "Landing Page Design",
        "Graphics for Streamers",
        "Social Media Design",
        "Business Cards & Stationery",
        "Email Design",
        "Illustration",
        "Resume Design",
        "Pattern Design",
        "Storyboards",
        "Packaging & Label Design",
        "Car Wraps",
        "Brochure Design",
        "Website Design",
        "Logo Design",
        "App Design",
        "Brand Style Guides",
        "UX Design",
        "Game Art",
        "Menu Design",
        "Poster Design",
        "Postcard Design",
        "Signage Design",
        "Vector Tracing",
        "Flyer Design",
        "Twitch Store",
        "Book Design",
        "Album Cover Design",
        "Podcast Cover Art",
        "Other",
      ],
    },

    {
      name: "Real Estate",
      subcategories: [
        "Commercial Real Estate",
        "Industrial Real Estate",
        "Residential Real Estate",
        "Other",
      ],
    },
    {
      name: "Education",
      subcategories: [
        "Social Sciences",
        "Humanities",
        "Languages",
        "Subjects",
        "Professor",
        "Other",
      ],
    },
    {
      name: "Nutrition",
      subcategories: [
        "Food Auditor",
        "Clinical Nutrition",
        "Sport Nutrition",
        "Oncological Nutrition",
        "Pediatric Nutrition",
        "Other",
      ],
    },

    {
      name: "Writing & Translation",
      subcategories: [
        "Articles and Blog Posts",
        "Proofreading & Editing",
        "Website Content",
        "UX Writing",
        "eBook Writing",
        "Resume Writing",
        "Cover Letter",
        "LinkedIn Profiles",
        "Other",
      ],
    },
    {
      name: "Botany",
      subcategories: [
        "Bryology",
        "Phytogeography",
        "Phytopathology",
        "Phytochemistry",
        "Geobotany",
        "Histology",
        "Paleobotany",
        "Cell Biology",
        "Cryptogamic Botany",
        "Phanerogamic Botany",
        "Other",
      ],
    },

    {
      name: "Entrepreneurship",
      subcategories: [
        "Scalable Entrepreneurship",
        "Entrepreneurship Incubator",
        "Opportunistic Entrepreneurship",
        "Small Business",
        "Social Entrepreneurship",
        "Technological Entrepreneurship",
        "Other",
      ],
    },
    {
      name: "Journalism",
      subcategories: [
        "Scientific Journalism",
        "Cultural Journalism",
        "Investigative Journalism",
        "Sports Journalism",
        "Event Journalism",
        "Economic Journalism",
        "Tourism Journalism",
        "Other",
      ],
    },
    {
      name: "Video & Animation",
      subcategories: [
        "Character Animation",
        "Animated GIFs",
        "Logo Animation",
        "Intros and Outros",
        "Lyric & Music Videos",
        "Animated Explainers",
        "Video Editing",
        "Short Video Ads",
        "Drone Videography",
        "Product Photography",
        "Local Photography",
        "Other",
      ],
    },
    {
      name: "Cybersecurity",
      subcategories: [
        "Computer Security Audit",
        "Cybersecurity Consulting",
        "Ethical Hacking",
        "Computer Forensics",
        "Cybercrime Investigation",
        "Computer Expertise",
        "Computer Network Security",
        "Other",
      ],
    },
    {
      name: "Aesthetics & Beauty",
      subcategories: [
        "Cosmetology",
        "Aesthetic Dermatology",
        "Image Design",
        "Stylist",
        "Other",
      ],
    },
    {
      name: "Psychology",
      subcategories: [
        "Social Psychology",
        "Basic Psychology",
        "Experimental Psychology",
        "Community Psychology",
        "Work Psychology",
        "Organizational Psychology",
        "Family Psychology",
        "Couple Psychology",
        "Sports Psychology",
        "Neuropsychology",
        "Marketing Psychology",
        "Clinical Psychology",
        "Consumer Psychology",
        "Cognitive Psychology",
        "Sexology",
        "Development Psychology",
        "Evolutionary Psychology",
        "Health Psychology",
        "Occupational Psychology",
        "Other",
      ],
    },
    {
      name: "Music & Audio",
      subcategories: [
        "Voice Over",
        "Mixing & Mastering",
        "Producers & Composers",
        "Singers & Vocalists",
        "Session Musicians",
        "Online Music Lessons",
        "Songwriters",
        "Beat Making",
        "Podcast Editing",
        "Instrumental Music",
        "Electronic Music Composer",
        "Symphonic Music Composer",
        "Other",
      ],
    },
    {
      name: "Film & Theatre",
      subcategories: [
        "Digital Animation",
        "Cinematography",
        "Audiovisual Communication",
        "Photography",
        "Theater and Performance",
        "Other",
      ],
    },
    {
      name: "Physical Fitness",
      subcategories: [
        "Body Pump",
        "CrossFit",
        "CXWORX",
        "HIIT",
        "Power Jump",
        "TRX Training",
        "Ballet Fit",
        "Body Balance",
        "Body Combat",
        "Other",
      ],
    },
    {
      name: "Chirology",
      subcategories: [
        "Other",
      ],
    },
    {
      name: "Programming & Technology",
      subcategories: [
        "Desktop Applications",
        "Online Coding Lessons",
        "Chatbots",
        "WordPress",
        "Website Builders",
        "Ecommerce Development",
        "Game Development",
        "Development for Streamers",
        "Mobile Apps",
        "Web Programming",
        "Other",
      ],
    },
    {
      name: "Fine Arts",
      subcategories: [
        "Architecture",
        "Cinema",
        "Dance",
        "Sculpture",
        "Literature",
        "Music",
        "Painting",
        "Other",
      ],
    },
    {
      name: "Photography",
      subcategories: [
        "Macro Photography",
        "Concert Photography",
        "Landscape Photography",
        "Aquatic Photography",
        "Artistic Photography",
        "Sports Photography",
        "Family Photography",
        "Documentary Photography",
        "Other",
      ],
    },
    {
      name: "Reiki",
      subcategories: [
        "Andean Reiki",
        "Celtic Reiki",
        "Rainbow Reiki",
        "Egyptian Reiki",
        "Karuna Reiki",
        "Tibetan Reiki",
        "Other",
      ],
    },
    {
      name: "Data",
      subcategories: [
        "Data Visualization",
        "Data Engineering",
        "Data Science",
        "Data Entry",
        "Databases",
        "Data Analytics",
        "Data Processing",
        "Other",
      ],
    },
    {
      name: "Audiovisuals",
      subcategories: [
        "Cinema",
        "Design",
        "Internet",
        "Marketing and Publicity",
        "Music and Advertising",
        "Music and Video Clips",
        "Radio",
        "Theater",
        "Television",
        "Video Games",
        "Other",
      ],
    },
    {
      name: "Gastronomy & Pastry",
      subcategories: [
        "Gourmet Gastronomy",
        "International Gastronomy",
        "Macrobiotic Gastronomy",
        "National Gastronomy",
        "Sustainable Gastronomy",
        "Vegan Gastronomy",
        "Vegetarian Gastronomy",
        "Other",
      ],
    },
    {
      name: "Software & Hardware",
      subcategories: [
        "Management Software",
        "Programming Software",
        "System Software",
        "App Software",
        "Storage Hardware",
        "Input and Output Hardware",
        "Processing Hardware",
        "Other",
      ],
    },
    {
      name: "Business",
      subcategories: [
        "Legal Consulting",
        "Financial Consulting",
        "Sales",
        "Customer Care",
        "Business Consulting",
        "HR Consulting",
        "International Business",
        "Information Technology",
        "Ecommerce Management",
        "Market Research",
        "Business Plans",
        "Other",
      ],
    },
    {
      name: "Martial Arts",
      subcategories: [
        "Traditional Martial Arts",
        "Modern Martial Arts",
        "Electic Martial Arts",
        "Other",
      ],
    },
    {
      name: "Management & Administration",
      subcategories: [
        "Business Administration",
        "Product Management",
        "Marketing Administration",
        "Human Resource Administration",
        "Financial Administration",
        "Public Administration",
        "Tourism Administration",
        "Virtual Assistant",
        "Other",
      ],
    },
    {
      name: "Tarot",
      subcategories: [
        "Rider Tarot Deck",
        "Marseille Tarot",
        "Egyptian Tarot",
        "Other",
      ],
    },
    {
      name: "Lifestyle",
      subcategories: [
        "Online Tutoring",
        "Gaming",
        "Astrology & Physics",
        "Modeling and Acting",
        "Fitness Lessons",
        "Dance Lessons",
        "Other",
      ],
    },
    {
      name: "Coaching",
      subcategories: [
        "Organizational Coaching",
        "Personal Coaching",
        "Systemic Coaching",
        "Coercive Coaching",
        "Life Coaching",
        "Cognitive Coaching",
        "Coaching with Emotional Intelligence",
        "Coaching with Neurolinguistic Programming",
        "Sports Coaching",
        "Ontological Coaching",
        "Other",
      ],
    },
    {
      name: "Hypnosis",
      subcategories: [
        "Traditional Hypnosis",
        "Autohypnosis",
        "Cognitive-Behavioral Hypnosis",
        "Ericksonian Hypnosis",
        "Other",
      ],
    },
    {
      name: "Technology",
      subcategories: [
        "API",
        "Science",
        "Computing",
        "Industry",
        "Artificial Intelligence",
        "Internet",
        "Robotics",
        "Other",
      ],
    },
    {
      name: "Law & Defense",
      subcategories: [
        "Labor and Security Law",
        "Business Law",
        "Notarial Law",
        "Criminal Law",
        "Private Law",
        "Public Law",
        "Tax Law",
        "Other",
      ],
    },
    {
      name: "Accounting & Finance",
      subcategories: [
        "International Economy",
        "Business Finance",
        "Family Finance",
        "Personal Finance",
        "Private Finance",
        "Macroeconomics",
        "Microeconomics",
        "Management Accounting",
        "Cost Accounting",
        "Industrial Engineering Accounting",
        "Financial Accounting",
        "Tax Accounting",
        "Activity-Based Accounting",
        "Public Accounting",
        "Other",
      ],
    },
    {
      name: "Computer Science",
      subcategories: [
        "Office Automation",
        "Backend Programming",
        "App Programming",
        "Machine Learning Programming",
        "Operating Systems Programming",
        "Video Game Programming",
        "Desktop Development",
        "Embedded Systems",
        "Frontend Development",
        "Full Stack Development",
        "Mobile Development",
        "Robotics",
        "Cybernetics",
        "Information Technology",
        "Computing",
        "Telematics",
        "General Programming",
        "Other",
      ],
    },
    {
      name: "Video Games Creation",
      subcategories: [
        "Concept Artist",
        "Graphic Design",
        "Game Design",
        "Arcade Games",
        "Adventure Games",
        "Sports Games",
        "Strategy Games",
        "Brain Games",
        "Tabletop Games",
        "Other",
      ],
    },
    {
      name: "Business Administration",
      subcategories: [
        "Production Management",
        "Administration and Finance",
        "Management and International Business",
        "Administration and Human Resources",
        "Other",
      ],
    },
    {
      name: "Culture & Literature",
      subcategories: [
        "Dramatic Literature",
        "Lyric Literature",
        "Narrative Literature",
        "Poetic Literature",
        "Other Literature",
        "Agricultural Literature",
        "Commercial Literature",
        "Historical Literature",
        "Industrial Literature",
        "Nomadic Literature",
        "Religious Culture",
      ],
    },
    {
      name: "Investments",
      subcategories: [
        "Fixed Income Investment",
        "Variable Income Investments",
        "Investment in Real Estate",
        "Investment in Stock Market",
        "Cryptocurrency",
        "Other",
      ],
    },
    {
      name: "Data Analysis",
      subcategories: [
        "Perspective Analysis",
        "Diagnostic Analysis",
        "Descriptive Analysis",
        "Predictive Analysis",
        "Other",
      ],
    },
    {
      name: "Legal Law",
      subcategories: [
        "Civil Law",
        "Family Law",
        "Property Rights",
        "Rights of Succession",
        "Administrative Law",
        "Tax Law",
        "Public International Law",
        "Labor Law",
        "Criminal Law",
        "Procedural Law",
      ],
    },
    {
      name: "Speech Therapy",
      subcategories: [
        "Geriatric Speech Therapy",
        "Children's Speech Therapy",
        "Neurology",
        "Clinical Speech Therapy",
        "School Speech Therapy",
        "Speech Therapy Specialist in Voice Disorders",
        "Other",
      ],
    },
    {
      name: "2D & 3D Animation",
      subcategories: [
        "3D Cartoon Animation",
        "Hyper-realistic 3D Animation",
        "Animation with Sand",
        "Traditional Animation",
        "Other",
      ],
    },
    {
      name: "Personal Development & Improvement",
      subcategories: [
        "Self-knowledge",
        "Self-esteem",
        "Communication",
        "Emotional Management",
        "Leadership",
        "Productivity",
        "Relationships",
        "Economic Improvement",
        "Spiritual Improvement",
        "Physical Improvement",
        "Intellectual Improvement",
        "Moral Improvement",
        "Social Skills and Communication",
        "Social Skills and Sales",
        "Other",
      ],
    },
    {
      name: "Archaeology",
      subcategories: [
        "Archaeoastronomy",
        "Environmental Archaeology",
        "Experiential Archaeology",
        "Phoenician Archaeology",
        "Forensic Archaeology",
        "Historical Archaeology",
        "Maritime Archaeology",
        "Prehistoric Archaeology",
        "Urban Archaeology",
        "Archaeopaleontology",
        "Archaeozoology",
        "Conservation",
        "Osteology",
        "Other",
      ],
    },
    {
      name: "Drawing",
      subcategories: [
        "Drawing Animated",
        "Artistic Drawing",
        "Conception Drawing",
        "Manufacturing Drawing",
        "Geometric Drawing",
        "Definition Drawing",
        "Freehand Drawing",
        "Natural Drawing",
        "Other",
      ],
    },
    {
      name: "Digital Marketing",
      subcategories: [
        "Digital Analytics",
        "SEM Advertising",
        "Conversion Rate Optimization (CRO)",
        "Email Marketing",
        "Inbound Marketing",
        "Affiliate Marketing",
        "Content Marketing",
        "SEO",
        "Social Networks",
        "Remarketing",
        "Social Media Marketing",
        "Other",
        "Marketing & Communication",
        "Video Marketing",
        "Public Relations",
      ],
    },
    {
      name: "Paleobotany & Paleoentnobotany",
      subcategories: [
        "Other",
      ],
    },
    {
      name: "Diet",
      subcategories: [
        "Other",
        "Low Calorie Diet",
        "Low Carbohydrate Diet",
        "Formula Diet",
        "Maintenance Diet",
        "Reduction Diet",
        "Interchangeable Diet",
        "Diet by Menu",
      ],
    },
    {
      name: "Meditation & Mindfulness",
      subcategories: [
        "Mindfulness Focused on Breathing",
        "Open Attention Mindfulness",
        "Body Scan Mindfulness",
        "Emotional Intelligence Mindfulness",
        "Mindfulness Goals",
        "Vipassana Mindfulness",
        "Cognitive Therapy Based on Mindfulness",
        "Other",
        "Chakra Meditation",
        "Kundalini Meditation",
        "Mantra Meditation",
        "Tonglen Meditation",
        "Transcendental Meditation",
        "Cipassana Meditation",
        "Zen Meditation",
      ],
    },
    {
      name: "Architecture",
      subcategories: [
        "Cognitive Architecture",
        "Computational Architecture",
        "Interior Architecture",
        "Systems Architecture",
        "Enterprise Architecture",
        "Naval Architecture",
        "Landscape Architecture",
        "Other",
      ],
    },
    {
      name: "2D & 3D Design",
      subcategories: [
        "3D Modeling",
        "Virtual Reality",
        "App Design",
        "Logo Design",
        "Other",
        "Digital & Multimedia Design",
        "BIM",
        "3D CAD",
        "CAD/CAM",
        "Product Design",
        "Generative Design",
        "Visual Effects",
      ],
    },
    {
      name: "Fashion",
      subcategories: [
        "Fashion Design",
        "Styling",
        "Writing and Communication",
        "Personal Shopper",
        "Pattern Maker",
        "Other",
      ],
    },
  ];
  